name: Build CI wheels

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.type }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      fail-fast:
        description: "Fail fast setting for building wheels."
        default: true
        required: false
        type: boolean
      deploy:
        description: "Allow deployment of build wheels."
        default: true
        required: false
        type: boolean
    secrets:
      PYPI_PASSWORD:
        description: "Token for pypi."
        required: false

jobs:
  auto-tag:
    name: Add release tag
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.autotag.outputs.tagsha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Autoadd release Tags
        uses: sbrodehl/action-autotag@v2
        id: autotag
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          source_file: "src/bison/__init__.py"
          # this is the semver regex https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string
          # with a capture group (around everything), but all other groups are non-capturing
          # double escape's where necessary
          extraction_regex: "__version__\\s*=\\s*[\\'\"]((?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)\\.(?:0|[1-9]\\d*)(?:-(?:(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+(?:[0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?)[\\'\"]"
          capture_group: 1
          tag_message: "Release"
          tag_format: "v{version}"
      - name: Show version
        if: steps.autotag.outputs.tagsha
        run: echo ${{ steps.autotag.outputs.tagsha }}

  deploy:
    name: Deploy to PyPI
    runs-on: ubuntu-latest
    needs: [auto-tag, build-wheels]
    if: ${{ needs.auto-tag.outputs.sha && inputs.deploy }}
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v2
        with:
          name: wheels
          path: ./dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}


  build-wheels:
    needs: [build_sdist]
    name: Build wheels on ${{ matrix.os }} (${{ matrix.cibw_archs }})
    runs-on: ${{ matrix.os }}
    env:
      CIBW_ARCHS_MACOS: "x86_64 arm64"
      CIBW_SKIP: "*_i686 *-win32 pp* *-musllinux_*"
    strategy:
      fail-fast: ${{ inputs.fail-fast }}
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-12]
        cibw_archs: ["auto"]
        include:
          - os: ubuntu-20.04
            cibw_archs: "aarch64"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version:  3.x

      - name: Set up QEMU
        if: matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.11.2

      - name: Build wheels for CPython 3.10 / 3.11
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp310-* cp311-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_24
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_24
          CIBW_BEFORE_ALL_LINUX: apt-get update && apt-get --yes --allow-downgrades --allow-remove-essential install libatlas-base-dev
          CIBW_BEFORE_BUILD: python -m pip install -U pip && python -m pip install -r requirements.txt
          CIBW_ARCHS: ${{ matrix.cibw_archs }}

      - name: Build wheels for CPython 3.7 / 3.8 / 3.9
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: "cp37-* cp38-* cp39-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014
          CIBW_BEFORE_ALL_LINUX: yum install -y atlas-devel
          CIBW_BEFORE_BUILD: python -m pip install -U pip && python -m pip install -r requirements.txt
          CIBW_ARCHS: ${{ matrix.cibw_archs }}

      - uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dist/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    needs: [auto-tag]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Switch to using Python 3.x
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build sdist
        run: python setup.py sdist

      - name: Check source distribution
        run: |
          mkdir -p /tmp/installation_dir && cd /tmp/installation_dir
          python -m pip install -v $( ls ${GITHUB_WORKSPACE}/dist/*.tar.gz )
          cd /tmp && python -c "import bison"
          cd ${GITHUB_WORKSPACE}

      - name: Store source distribution
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./dist/*tar.gz

      - name: Publish to PyPI
        if: ${{ needs.auto-tag.outputs.sha && inputs.deploy }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip_existing: true
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}

  testing:
    needs: [build_sdist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        name: Switch to using Python 3.x
        with:
          python-version: 3.x

      - name: Build and install
        run: pip install --verbose .[test]

      - name: Run Tests
        run: cd tests && pytest
