name: CI build

on:
  push:
    branches:
      - 'main'
      - 'master'
    workflow_dispatch:

jobs:
  CIBW:
    uses: lukeparser/pybison/.github/workflows/cibuildwheel.yml@master
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
