name: Deploy to PyPI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 2.7
            pep-425-tag: 'cp27-cp27m'
          - python-version: 3.5
            pep-425-tag: 'cp35-cp35m'
          - python-version: 3.6
            pep-425-tag: 'cp36-cp36m'
          - python-version: 3.7
            pep-425-tag: 'cp37-cp37m'
          - python-version: 3.8
            pep-425-tag: 'cp38-cp38m'
          - python-version: 3.9
            pep-425-tag: 'cp39-cp39m'
    runs-on: ubuntu-latest
    name: "Deploy to PyPI"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
            python-version:  ${{ matrix.python-version }}
      - name: Build manylinux Python wheels
        uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
        with:
          python-versions: ${{ matrix.pep-425-tag }}
          build-requirements: 'six Cython'
          system-packages: 'atlas-devel'
