name: Latest Versions

on:
  push:
    branches:
      - '*'
      - '!master'

jobs:

  build-manylinux:
    name: manylinux (${{ matrix.pep-425-tag }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: 3.8
            pep-425-tag: 'cp38-cp38'
          - python-version: 3.9
            pep-425-tag: 'cp39-cp39'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Build wheel for ${{ matrix.pep-425-tag }} on manylinux
        uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
        with:
          python-versions: ${{ matrix.pep-425-tag }}
          build-requirements: 'six Cython'
          system-packages: 'atlas-devel'
      - name: List builds
        run: ls -la ./dist/

  build-macos:
    name: macOS (py${{ matrix.python-version }})
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel setuptools
      - name: Build wheel for ${{ matrix.python-version }} on macOS
        run: python setup.py bdist_wheel
      - name: List builds
        run: ls -la ./dist/

  build-windows:
    name: Windows (py${{ matrix.python-version }})
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version:  ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel setuptools
      - name: Build wheel for ${{ matrix.python-version }} on Windows
        run: python setup.py bdist_wheel
      - name: List builds
        run: dir dist
