name: Build CI wheels

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'

jobs:
  call-build-step:
    uses: ./.github/workflows/cibuildwheel@latest
    with:
      fail-fast: false
      deploy: false
