name: Build CI wheels

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!main'

jobs:
  call-build-step:
    uses: lukeparser/pybison/.github/workflows/cibuildwheel.yml@master
    with:
      fail-fast: false
      deploy: false
